#!/usr/bin/env python3
"""
Regression lock for the 4 human-verified origin fractions named in the task
brief (tasks/prefab-compiler-brief.md, truth values from
tasks/worldmap-report.md's §终审返修): s1_1=(0.495,0.659),
s1_2=(0.460,0.532), llbt=(0.500,0.500), btnnmg=(0.668,0.487).

Runs against a small self-contained XML fixture (tests/fixtures/
worldmap_nodes.xml, generated by make_fixture.py from OtherMat1.swf's
swf2xml) rather than the vendor extraction, so this test has no dependency
on vendor/ or tmp/ being present on disk.

Run: python3 -m unittest discover -s tools/prefab-compiler/tests
"""
import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from compiler import SwfIndex, compile_symbol  # noqa: E402

FIXTURES = os.path.join(os.path.dirname(__file__), 'fixtures')


class OriginRegressionTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.idx = SwfIndex(os.path.join(FIXTURES, 'worldmap_nodes.xml'))

    def _origin(self, cid):
        result = compile_symbol(self.idx, cid)
        self.assertEqual(result['warnings'], [], f'cid={cid} produced unexpected warnings: {result["warnings"]}')
        return result['root']['originFrac']

    def test_s1_1(self):
        o = self._origin(857)
        self.assertAlmostEqual(o['x'], 0.495, places=3)
        self.assertAlmostEqual(o['y'], 0.659, places=3)

    def test_s1_2(self):
        o = self._origin(871)
        self.assertAlmostEqual(o['x'], 0.460, places=3)
        self.assertAlmostEqual(o['y'], 0.532, places=3)

    def test_llbt(self):
        o = self._origin(973)
        self.assertAlmostEqual(o['x'], 0.500, places=3)
        self.assertAlmostEqual(o['y'], 0.500, places=3)

    def test_btnnmg(self):
        o = self._origin(931)
        self.assertAlmostEqual(o['x'], 0.668, places=3)
        self.assertAlmostEqual(o['y'], 0.487, places=3)

    def test_resolve_by_class_name_matches_numeric_id(self):
        # 973/931 have no linked class name in this SWF (matches worldmap-report:
        # decoration symbols are referenced by depth inside SelectPLace, not
        # individually linked) -- but a linked one (llbt's containing symbol
        # isn't linked either in this fixture) should still resolve by id.
        # Sanity: numeric-string resolution behaves identically to int.
        self.assertEqual(self.idx.resolve('857'), self.idx.resolve(857))


if __name__ == '__main__':
    unittest.main()
